name: Update mineral_results.json

on:
  workflow_dispatch:  # Ermöglicht manuelles Auslösen
  schedule:
    - cron: '0 0 1 */3 *'  # Alle 3 Monate am ersten Tag um Mitternacht

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run script to update JSON
        run: python request.py 
        env:
          MINDAT_API_KEY: ${{ secrets.MINDAT_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/mineral_results.json --force
          git commit -m "Update mineral_results.json" || echo "No changes to commit"
          git push
          git commit -m "Update mineral_results.json"
          git push
        env:
          MINDAT_API_KEY: ${{ secrets.MINDAT_API_KEY }}
